# Configuracion del Servidor
# Estas propiedades pueden ser sobrescritas por variables de entorno:
# SERVER_PORT
# SERVER_CONTEXT_PATH
server.port=8080
server.context-path=NexusBE/api

# Configuracion de la Base de Datos
# Estas propiedades pueden ser sobrescritas por variables de entorno:
# DB_URL
# DB_USER
# DB_PASSWORD
db.url=jdbc:postgresql://127.0.0.1:5433/nexus_db
db.user=admin_nexus
db.password=admin_password_123
